class Egypt {
  static List<String> governorates = [
    'Alexandria',
    'Aswan',
    'Asyut',
    'Beheira',
    'Beni Suef',
    'Cairo',
    'Dakahlia',
    'Damietta',
    'Faiyum',
    'Gharbia',
    'Giza',
    'Ismailia',
    'Kafr El Sheikh',
    'Luxor',
    'Matruh',
    'Minya',
    'Monufia',
    'New Valley',
    'North Sinai',
    'Port Said',
    'Qalyubia',
    'Qena',
    'Red Sea',
    'Sharqia',
    'Sohag',
    'South Sinai',
    'Suez'
  ];
  static List<String> cairo = [
    '15 May city',
    'Abasiya',
    'Ain shames',
    'Al Amiriyyah',
    'Al Manial',
    'Al Maza',
    'Ataba',
    'Bab al_sheria',
    'Badr City',
    'Basaten',
    'Boluq',
    'Dar Elsalam',
    'Darb al Ahmer',
    'Darrasa',
    'DownTown Cairo',
    'El Fostat',
    'Ezbet Elnakhl',
    'Gamalya',
    'Garden City',
    'Gasr El Suez',
    'Hadyayek Helwan',
    'Helwan',
    'Helioplis',
    'Helmet alGaded',
    'Helmet alZayton',
    'Katamya',
    'Ma\'sara',
    'Maadi',
    'Marg',
    'Masr El Kadema',
    'Mokattam',
    'Moski',
    'Nasr city',
    'New cairo',
    'El Rehab City'
  ];
}
